pyminds/urls.py
from django.conf.urls import include, url


urlpatterns = [
    url(r'', include('review.urls', namespace='review')),
    url(r'', include('review.endpoint_urls', namespace='review-endpoints')),
]

review/urls.py
#! coding: utf-8
from django.conf.urls import url

from .views import *


urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^schedule/(.+)/$', schedule_page, name='schedule_page'),
    url(r'^questions/$', questions, name='questions'),
    url(r'^closed_questions/$', closed_questions, name='closed_questions'),
    url(r'^question/forgot/$', ForgotQuestionView.as_view(), name='forgot_question')
]

review/models.py
import datetime

from django.db import models


class ReviewManager(models.Manager):

    def closeds(self):
        """
        Return all closed reviews. Closed reviews
        are reviews without open schedules.
        """
        return self.exclude(
            pk__in=Schedule.objects.filter(
                checked=False
            ).values('review__pk'))


class Review(models.Model):

    objects = ReviewManager()

    def __str__(self):
        return 'Review %s' % self.pk


class ScheduleQuerySet(models.QuerySet):

    def update_to_emailed(self):
        return self.to_send_email().update(emailed=True)

    def to_send_email(self):
        """
        Return the schedules to send over email
        """
        return self.filter(
            date__lte=datetime.datetime.today(),
            emailed=False
        )

    def currents(self):
        """
        Return the schedules in progress.
        """
        return self.filter(
            date__lte=datetime.datetime.today(),
            checked=False
        ).order_by('review').distinct('review__id')


class Schedule(models.Model):
    class Meta:
        ordering = ['date']

    checked = models.BooleanField(default=False)
    emailed = models.BooleanField(default=False)
    rate = models.IntegerField(null=True, blank=True)
    date = models.DateField()
    review = models.ForeignKey(Review, related_name='questions')

    objects = ScheduleQuerySet.as_manager()

    def __str__(self):
        return 'Schedule {} {}'.format(
            self.review.pk,
            self.date.strftime("%d/%m/%Y")
        )

    @classmethod
    def close_last_schedules(cls, review):
        today = datetime.datetime.today()
        schedules = cls.objects.filter(
            date__lte=today,
            checked=False,
            review=review
        )
        schedules.update(checked=True)

    @classmethod
    def get_next_schedule(cls):
        today = datetime.datetime.today()
        schedules = cls.objects.filter(checked=False).exclude(date__lte=today)
        if schedules:
            return schedules[0]
        else:
            return None


class QuestionManager(models.Manager):

    def closeds(self):
        """
        Return the questions with closed reviews.
        """
        return self.filter(review__in=Review.objects.closeds())


class Question(models.Model):
    text = models.CharField(max_length=140, verbose_name="")
    date = models.DateTimeField(default=datetime.datetime.today())
    forgot = models.BooleanField(default=False)
    reference_link = models.URLField(blank=True, verbose_name="")
    review = models.ForeignKey(Review, null=True, blank=True)

    objects = QuestionManager()

    def update_forgot(self):
        self.forgot = True
        self.save()


class Tag(models.Model):
    name = models.CharField(max_length=200)
    questions = models.ManyToManyField(Question, related_name='tags')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return 'Review {}'.format(self.name)

review/forms.py
from django import forms
from .models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude = ('date', 'review', 'forgot')
        widgets = {
            'text': forms.Textarea(attrs={"placeholder": "Insert your question here..."}),
            'reference_link': forms.TextInput(attrs={"placeholder": "Reference link..."})
        }

    tags = forms.CharField(max_length=100, label='', required=False,)

review/views.py
import json

from random import shuffle

from django.views.generic import FormView
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import View
from django.http import HttpResponse

from review.forms import QuestionForm
from review.models import Question, Schedule, Tag
from review.helpers import create_tags, create_all


class HomeView(FormView):
    success_url = reverse_lazy('review:home')
    template_name = 'home.html'
    form_class = QuestionForm

    def form_valid(self, form):
        question = form.save()
        tags = form['tags'].value()
        if tags:
            create_tags(question, tags)
        create_all()
        response = super(HomeView, self).form_valid(form)
        return response

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['schedules'] = Schedule.objects.currents()
        context['next_schedule'] = Schedule.get_next_schedule()
        context['count_schedules'] = Schedule.objects.filter(
            checked=False
        ).count()
        context['number_next_question'] = Question.objects.all().count() + 1
        tags_name = [str(t['name']) for t in Tag.objects.all().values('name')]
        context['tags'] = ','.join(tags_name)
        return context


def schedule_page(request, schedule_id):
    schedule = get_object_or_404(Schedule, id=schedule_id)

    if request.method == 'POST':
        review = schedule.review
        Schedule.close_last_schedules(review)
        return redirect('/')

    return render(request, 'schedule.html', {'schedule': schedule})


def questions(request):
    questions = Question.objects.all()
    quant = request.GET.get('quant', None)
    tags = request.GET.get('tags', None)
    if tags:
        tags_name = tags.split(',')
        tags = Tag.objects.filter(name__in=tags_name)
        questions = questions.filter(tags__in=tags)
    if quant:
        quant = int(quant)
        questions = list(questions[:quant])
        shuffle(questions)
    return render(request, 'questions.html', {'questions': questions})


def closed_questions(request):
    questions_list = Question.objects.closeds().order_by('?')[:10]
    return render(request, 'questions.html', {'questions': questions_list})


class ForgotQuestionView(View):

    def post(self, request, *args, **kwargs):
        question_pk = request.POST.get('pk')
        question = get_object_or_404(Question, pk=question_pk)
        question.update_forgot()
        return HttpResponse(
            json.dumps({'message': 'Success updated'}),
            content_type="application/json")

review/templates/base.html
{% load static %}

<!DOCTYPE HTML>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.tagit.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/tagit.ui-zendesk.css' %}" />
	
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="{% static 'js/tag-it.js' %}" type="text/javascript" charset="utf-8"></script>

	{% block extra_head %}{% endblock %}

	<title></title>

</head>
<body>

    <div id="top"></div>
	<header>

        <h1><a href="{% url 'review:home' %}">PyMinds     </a></h1>

	</header>
	<div id="content">

		<div class="left">
            {% block content_left %}{% endblock %}
        </div>
		<div class="line"></div>

		<div class="right">
            {% block content_right %}{% endblock %}
		</div>

    </div>
<!-- <footer> <ul>
             </ul></footer> -->
</body>
</html>

review/templates/home.html
{% extends 'base.html' %}

        {% block extra_head%}
            <script type="text/javascript">
                $(document).ready(function() {
                    var sampleTags = document.getElementById("myVar").value.split(',');
                    $('#id_tags').tagit({
                        availableTags: sampleTags
                    });

                    $('ul.tagit input[type="text"]').attr('placeholder','tags...');
                });
            </script>

        {% endblock %}


        {% block content_left %}
            <h3 class="title">Question {{number_next_question}}</h3>
            <form method='POST' action=''>
                {% csrf_token %}
                {{ form }}
                <input type="submit" id="btSubmit" value="Raise">
            </form>
            <input type="hidden" id="myVar" name="variable" value="{{tags}}">
        {% endblock %}

        {% block content_right %}
            <h4>Schedules: {{count_schedules}}
                next {{ next_schedule.date|date:"d/m/Y"  }}</h4>
            <ul>
                {% for s in schedules %}
                    <li><a href="{% url 'review:schedule_page' s.id %}">{{s}}</a></li>
                {% endfor %}
            </ul>
            <ul>
                <li class="old"><a href="{% url 'review:closed_questions' %}"> Review Questions</a></li>
            </ul>
		{% endblock %}

review/templates/questions.html
{% extends 'base.html' %}

{% block content_left %}
<!--<h1 class="title">{{schedule}}</h1>-->
<!--<h3 class="subtitle">{{ schedule.review }}</h3>-->
    <ul class="schedule-ul">
    {% for q in questions %}
        <li>
            {{ q.text }} <br/>
            {{ q.reference_link }}
            {% for tag in q.tags.all %}
                <span class="mytags">{{tag.name}}</span>
            {% endfor %}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

review/templates/schedule.html
{% extends 'base.html' %}

{% block extra_head%}

    <script type="text/javascript">
        $(document).ready(function() {
            $("#forgot-question").live("click", function() {
                var pk = $(this).attr("question-id");
                $.post(
                    "{% url 'review:forgot_question' %}",
                    {pk: pk,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                    }
                );
            });
        });
    </script>

{% endblock %}

{% block content_left %}

<h1 class="title">{{schedule}}</h1>
<h3 class="subtitle">{{ schedule.review }}</h3>
    <ul class="schedule-ul">
    {% for question in schedule.review.question_set.all %}
        <li>
            {{ question.text }} <br/>
            {{ question.reference_link }}
            {% for tag in question.tags.all %}
                <span class="mytags">{{tag.name}}</span>
            {% endfor %}
            <a href="#" id="forgot-question" question-id="{{ question.id }}" class="btForgot">Forget</a>
        </li>
    {% endfor %}
    </ul>
    <form class="schedule-form" method="post" action="">
        {% csrf_token %}
        <input id="btSubmit" type="submit" value="submeter"/>
        </form>

{% endblock %}